# This is a basic workflow to help you get started with Actions

name: Semgrep

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor "= 'dependabot[bot]')
    steps:
    - uses: action/checkout@v2
    - uses: returntocorp/semgrep-action@v1
    with:
      auditOn: push
      publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
      publishDeplyment: 2682
