name: Semgrep
on:
    pull_request: {}
    push:
    branches:
    - main
    - master

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
    - uses: action/checkout@v2
    - uses: returntocorp/semgrep-action@v1
    with:
      auditOn: push
      publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
      publishDeplyment: 2682
